export const LightTheme = {
  Light_THEME: "true",
  globalBackground: "#fff",
  color: "#000",
  rcolor: "#fff",
  upperChildTextColor: "#475569",
  childtextColor: "#616e7c",
  DarkImgDisplay: "block",
  LightImgDisplay: "none",
  LogoutBtn: "#3b82f6",
  ContactSupport: "#231f20",
  SubHeaderContainer: "#ebebeb",
  SubHeaderIconContainer: "#d7dfe9",
  SmallTextColor: " #7e858e",
  LoginWrapper: "#f9f9f9",
  boxShadow: "0px 0px 10px 15px #f1f1f1",
  InputColor: "#000",
  SideContentContainerBGColor: "#f1f1f1",
  SearchInputBGColor: "#fff",
  SearchImgBGColor: "#ebebeb",
  BLANK_LINE: "#ccc",
  LOGOUT_BGCOLOR: "#fff",
  LOGOUT_MSG: "#00306e",
  LINK_BGCOLOR: "#d7dfe9",
};

export const DarkTheme = {
  Light_THEME: "false",
  globalBackground: "#212121",
  color: "#fff",
  rcolor: "#000",
  upperChildTextColor: "#fff",
  childtextColor: "#94a3b8",
  DarkImgDisplay: "none",
  LightImgDisplay: "block",
  LogoutBtn: "#fff",
  ContactSupport: "#fff",
  SubHeaderContainer: "#313131",
  SubHeaderIconContainer: " #000000",
  SmallTextColor: "#94a3b8",
  LoginWrapper: "#212121",
  boxShadow: "none",
  InputColor: "#e2e8f0",
  SideContentContainerBGColor: "#181818",
  SearchInputBGColor: " transparent",
  SearchImgBGColor: " #383838",
  BLANK_LINE: "#94a3b8",
  LOGOUT_BGCOLOR: "#231f20",
  LOGOUT_MSG: "#fff",
  LINK_BGCOLOR: "#383838",
};
